config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :genres
    resources :movies
  end
  post "notifications/user_update" => "notifications#user_update"
  put "notifications" => "notifications#seen"
  post "notifications/decline" => "notifications#decline"
  post "notifications/accept" => "notifications#accept"
  put "notifications/show_list" => "notifications#show_list"
  get "notifications/follows" => "notifications#follow_list"
  resources :relationships
  resources :genres, only: :show
  resources :searchs, only: :index
  resources :users
  resources :bookmarks, only: [:index, :create,:destroy]
  resources :movies
  resources :rates, only: :create
  resources :comments, only: [:create, :destroy]
  root "static_pages#home"
  get "about" => "static_pages#about"
end

app/views/layouts/admin/_side_bar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to admin_root_path do %>
        <%= image_tag "logo.jpeg", class: "header-img" %>
      <% end %>  
    </li>
    <li class="panel-group">
      <%= link_to admin_root_path do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>  
        <%= t :dash_board %>
      <% end %>
    </li>
    <li class="panel-group">
      <a data-toggle="collapse" href="#user">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
        <%= t "user.user" %>
      </a>
      <ul id="user" class="panel-collapse collapse">
        <li>
          <%= link_to t("navbar.user"), admin_users_path %>
        </li>
      </ul>
    </li>
    <li class="panel-group">
      <a data-toggle="collapse" href="#category">
        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>  
        <%= t "genre.genre" %>
      </a>
      <ul id="category" class="panel-collapse collapse">
        <li>
          <%= link_to t(:new_genre), new_admin_genre_path %>
        </li>
        <li>
          <%= link_to t("index"), admin_genres_path %>
        </li>
      </ul>
    </li>
    <li class="panel-group">
      <a data-toggle="collapse" href="#course">
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>  
        <%= t "movie.movie" %>  
      </a>
      <ul id="course" class="panel-collapse collapse">
        <li>
          <%= link_to t("navbar.new_movie"), new_admin_movie_path %>
        </li>
        <li>
          <%= link_to t("index"), admin_movies_path %>
        </li>
      </ul>
    </li>
    <li class="panel-group">
      <a data-toggle="collapse" href="#account">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>  
        <%= t :account %>
      </a>
      <ul id="account" class="panel-collapse collapse">
        <li>
          <%= link_to t("navbar.logout"), destroy_user_session_path, 
            method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application",
      media: "all","data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/admin/side_bar" %> 
      <div id="page-content-wrapper">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>