config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :genres
    resources :movies
  end
  post "notifications/user_update" => "notifications#user_update"
  put "notifications" => "notifications#seen"
  post "notifications/decline" => "notifications#decline"
  post "notifications/accept" => "notifications#accept"
  put "notifications/show_list" => "notifications#show_list"
  get "notifications/follows" => "notifications#follow_list"
  resources :relationships
  resources :genres, only: :show
  resources :searchs, only: :index
  resources :users
  resources :bookmarks, only: [:index, :create,:destroy]
  resources :movies
  resources :rates, only: :create
  resources :comments, only: [:create, :destroy]
  root "static_pages#home"
  get "about" => "static_pages#about"
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies, through: :movie_genres
  has_many :movie_genres, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :find_genre, only: [:destroy, :edit, :update]

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end
  

  def edit  
  end

  def update
    if @genre.update genre_params
      flash[:success] = t "genre.update"
    else
      flash[:danger] = t "flash.fail"
    end
    redirect_to admin_genres_path  
  end

  def create
    @genre = Genre.new genre_params
    if @genre.save
      flash[:success] = t "genre.success"
      redirect_to admin_genres_path
    else
      render :new
    end   
  end

  def destroy
    if @genre.destroy
      flash[:success] = t "genre.deteled"
    else
      flash[:danger] = t "flash.fail"
    end
    redirect_to admin_genres_path     
  end

  def update
    if @genre.update genre_params
      flash[:success] = t "categories.update"
    else
      flash[:danger] = t "flash.fail"
    end
    redirect_to admin_genres_path
  end

  private
  def verify_admin
    unless current_user.admin?
      flash[:danger] = t :not_have_permission
      redirect_to root_path
    end 
  end
  def find_genre
    @genre = Genre.find_by id: params[:id]
    if @genre.nil?
      flash[:danger] = t "genre.empty"
      redirect_to admin_root_path
    end
  end
  def genre_params
    params.require(:genre).permit :name
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :find_genre
  
  def show
    @movies = @genre.movies.page(params[:page]).per 8
  end

  def find_genre
    @genre = Genre.find_by id: params[:id]
    if @genre.nil?
      flash[:now][:danger] = t "user.empty"
      redirect_to admin_root_path
    end
  end
end

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @genre] do |f| %>
      <%= render "shared/error_messages", object: @genre %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t("new"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<table width="100%">
  <tr style="line-height: 30px">
    <th><%= :name %></th>
    <th style="text-align: right;"><%= t :action %></th>
  </tr>
  <% @genres.each do |genre| %>
    <tr style="line-height: 30px">
      <td><%= link_to genre.name, "#" %></td>
      <td style="text-align: right;">
        <%= link_to "", edit_admin_genre_path(genre), 
          class: "glyphicon glyphicon-edit" %>
        <%= link_to "", admin_genre_path(genre),
          method: :delete, data: {confirm: t("flash.confirm")}, 
          class: "glyphicon glyphicon-trash" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/genres/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @genre] do |f| %>
      <%= render "shared/error_messages", object: @genre %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <br/>

      <%= f.submit t("new"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>