config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :genres
    resources :movies
  end
  post "notifications/user_update" => "notifications#user_update"
  put "notifications" => "notifications#seen"
  post "notifications/decline" => "notifications#decline"
  post "notifications/accept" => "notifications#accept"
  put "notifications/show_list" => "notifications#show_list"
  get "notifications/follows" => "notifications#follow_list"
  resources :relationships
  resources :genres, only: :show
  resources :searchs, only: :index
  resources :users
  resources :bookmarks, only: [:index, :create,:destroy]
  resources :movies
  resources :rates, only: :create
  resources :comments, only: [:create, :destroy]
  root "static_pages#home"
  get "about" => "static_pages#about"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
 has_many :recived_notifications, class_name:  "Notification",
                                 foreign_key: "reciver_id",
                                 dependent:   :destroy
 has_many :sent_notifications, class_name:  "Notification",
                                  foreign_key: "sender_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :comments, dependent: :destroy
  has_many :rates
  has_many :bookmarks, dependent: :destroy
  enum role: {admin: 1, user: 0}
  mount_uploader :avatar, AvatarUploader
  scope :sended_user, ->user_id{where "SELECT reciver_id FROM notifications WHERE sender_id = ? 
    AND reciver_status != ? AND content =? ", user_id, 2, "follow"}

  def has_voted movie
    movies = self.rates.collect {|r| r.movie}
    movies.include? movie
  end

  # Follows a user.
  def follow other_user
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following? other_user
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.user_name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"] || session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
      user.email = data["email"]
    end
  end
end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_user, only: [:edit, :update, :destroy, :show]
  
  def index
    @search = User.search params[:q]
    @users = @search.result.page params[:page]
  end

  def edit
    @users = User.all
  end
  
  def show  
  end

  def destroy
    if @user.destroy
      flash[:success] = t "user.deleted"
    else
      flash[:danger] = t "flash.fail"
    end
    redirect_to admin_users_path
  end

  def update
    if @user.update user_params
      flash[:success] = "success"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit :user_name, :avatar, :age, :phone_number
  end

  def find_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = "User not exist"
      redirect_to admin_root_path
    end
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  # before_filter :configure_permitted_parameters
  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up).push(:user_name)
  # end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: :show
  
  def show
    @movies = []
    bms= @user.bookmarks
    bms.each do |bm|
      @movies << bm.movie
    end
    # @ms = Movie.all
    @movies = Kaminari.paginate_array(@movies).page(params[:page]).per(8)
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(8)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(8)
    render 'show_follow'
  end
  
  private 
  def find_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:now][:danger] = "User not exist"
      redirect_to admin_root_path
    end
  end
end

app/views/admin/users/_condition_fields.html.erb
<div class="field category">
  <div class="wrapper">
    <div class="col-md-3">
      <%= f.attribute_fields do |a| %>
        <%= a.attribute_select associations: [:category], class: "form-control" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= f.predicate_select %>
    </div>
    <div class="col-md-4">
      <%= f.value_fields do |v| %>
        <%= v.text_field :value, class: "form-control" %>
      <% end %>
    </div> 
    <%= link_to t(:remove), "#", id: "remove_fields", class: "btn btn-warning" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user] do |f| %>      
      <div class="field">
        <%= f.label :user_name %>
        <%= f.text_field :user_name, autofocus: true, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :age %>
        <%= f.number_field :age, autofocus: true, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :phone_number %>
        <%= f.number_field :phone_number, autofocus: true, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: "form-control" %>
        <%= f.hidden_field :avatar_cache %>
      </div>
      <br/>
<%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<% provide :title, t("user.index") %>
<h3><%= t "user.index" %></h3>
<%= search_form_for @search, url: admin_users_path do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <div><%= link_to_add_fields t("user.add_condition"), 
    f, :condition %>
  </div>
  <div class="action" style="width: 120px; float: right; margin-top: 25px; margin-right: -80px;"><%= f.submit t("user.search"), 
    class: "btn btn-primary" %></div>
<% end %>

<table id="table_wrapper">
  <tr style="line-height: 30px;">
    <th><%= sort_link @search, :user_name, t("table.name") %></th>
    <th style="text-align: right;"><%= t :action %></th>
  </tr>
  <% @users.each do |user| %>
    <tr style="line-height: 30px;">
      <td><%= link_to user.user_name, admin_user_path(user) %></td>
      <td style= "text-align: right;">
        <%= link_to "", edit_admin_user_path(user), 
          class: "glyphicon glyphicon-edit" %>
        <%= link_to "", admin_user_path(user),
          method: :delete, data: {confirm: t("flash.confirm")}, 
          class: "glyphicon glyphicon-trash" %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @users %>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="page-header">
    <section class="col-sm-4">
      <div id="image_size">
        <%= image_tag @user.avatar %>
      </div>
    </section>    
    <section class="user_info col-sm-4">
      <h1>email: <%= @user.email %></h1>
      <h1>name: <%= @user.user_name %></h1>
      <h1>age: <%= @user.age %></h1>
      <h1>phone: <%= @user.phone_number %></h1>
    </section>
  </div>
</div>  